// ─── The Heidelberg Catechism (1563) ──────────────────────────
// Drafted by Zacharias Ursinus and Caspar Olevianus at the request of
// Elector Frederick III of the Palatinate. The most pastoral and warm
// of the Reformation catechisms — divided into three parts: our misery,
// our deliverance, and our gratitude. 129 questions across 52 Lord's
// Days — one for every week of the year.
//
// We have lightly modernized the wording for readability while
// preserving the doctrinal substance. The Catechism is in the public
// domain.

export type CatechismQA = {
  q: number;
  question: string;
  answer: string;
};

export type LordsDay = {
  ld: number;        // 1..52
  part: 1 | 2 | 3;   // 1 Misery · 2 Deliverance · 3 Gratitude
  theme: string;
  qas: CatechismQA[];
};

export const catechismParts: Record<1 | 2 | 3, { name: string; sub: string }> = {
  1: { name: "Of Our Misery", sub: "What we are without Christ — Lord's Days 2–4" },
  2: { name: "Of Our Deliverance", sub: "How we are rescued through Christ — Lord's Days 5–31" },
  3: { name: "Of Our Gratitude", sub: "How we live in response to grace — Lord's Days 32–52" },
};

export const heidelberg: LordsDay[] = [
  {
    ld: 1,
    part: 2, // The opening is usually treated as the doorway into the whole
    theme: "Your only comfort in life and death",
    qas: [
      {
        q: 1,
        question: "What is your only comfort in life and in death?",
        answer:
          "That I, with body and soul, both in life and in death, am not my own, but belong to my faithful Savior Jesus Christ; who, with His precious blood, has fully satisfied for all my sins, and delivered me from all the power of the devil; and so preserves me that without the will of my heavenly Father not a hair can fall from my head; indeed, all things must work together for my salvation. Therefore, by His Holy Spirit, He also assures me of eternal life, and makes me sincerely willing and ready, from now on, to live for Him.",
      },
      {
        q: 2,
        question: "How many things are necessary for you to know, that in this comfort you may live and die happily?",
        answer:
          "Three: first, how great my sin and misery are; second, how I am delivered from all my sins and their misery; third, how I am to be thankful to God for such deliverance.",
      },
    ],
  },
  {
    ld: 2,
    part: 1,
    theme: "Our misery — knowing our sin",
    qas: [
      { q: 3, question: "From where do you know your misery?", answer: "From the law of God." },
      {
        q: 4,
        question: "What does the law of God require of us?",
        answer:
          "Christ teaches us in summary, Matthew 22: 'You shall love the Lord your God with all your heart, with all your soul, with all your mind, and with all your strength. This is the great and first commandment. And the second is like it: You shall love your neighbor as yourself. On these two commandments hang all the Law and the Prophets.'",
      },
      {
        q: 5,
        question: "Can you keep all this perfectly?",
        answer:
          "By no means; for by nature I am prone to hate God and my neighbor.",
      },
    ],
  },
  {
    ld: 3,
    part: 1,
    theme: "Our fall — what went wrong",
    qas: [
      {
        q: 6,
        question: "Did God create man so wicked and perverse?",
        answer:
          "By no means. God created man good, and after His own image — that is, in true righteousness and holiness — that he might rightly know God his Creator, love Him with all his heart, and live with Him in eternal happiness, to praise and glorify Him.",
      },
      {
        q: 7,
        question: "From where, then, comes this depraved nature of man?",
        answer:
          "From the fall and disobedience of our first parents, Adam and Eve, in paradise, where our nature became so corrupt that we are all conceived and born in sin.",
      },
      {
        q: 8,
        question: "Are we so corrupt that we are wholly unable to do any good, and inclined to all evil?",
        answer:
          "Yes, indeed; unless we are regenerated by the Spirit of God.",
      },
    ],
  },
  {
    ld: 4,
    part: 1,
    theme: "God's justice and our hopelessness apart from Him",
    qas: [
      {
        q: 9,
        question: "Is not God then unjust to require of man in His law what he cannot perform?",
        answer:
          "No; for God so made man that he could perform it; but man, by the instigation of the devil and his own willful disobedience, deprived himself and all his descendants of those gifts.",
      },
      {
        q: 10,
        question: "Will God allow such disobedience to go unpunished?",
        answer:
          "By no means; but He is terribly displeased with our original as well as our actual sins, and will punish them in His just judgment, as He has declared: 'Cursed is everyone who does not abide by all things written in the book of the law, to do them.'",
      },
      {
        q: 11,
        question: "But is not God also merciful?",
        answer:
          "God is indeed merciful, but He is also just. His justice requires that sin, committed against His infinite majesty, must also be punished with extreme — that is, eternal — punishment of body and soul.",
      },
    ],
  },
  {
    ld: 5,
    part: 2,
    theme: "Who can be our Mediator?",
    qas: [
      {
        q: 12,
        question: "Since, then, by the righteous judgment of God we deserve temporal and eternal punishment, how may we escape this punishment and be received again into favor?",
        answer:
          "God will have His justice satisfied; and therefore we must make full satisfaction either by ourselves or by another.",
      },
      {
        q: 13,
        question: "Can we ourselves make this satisfaction?",
        answer:
          "By no means; on the contrary, we daily increase our debt.",
      },
      {
        q: 14,
        question: "Can any creature make satisfaction for us?",
        answer:
          "None; for first, God will not punish in any other creature what man has committed; further, no creature can sustain the burden of God's eternal wrath against sin, and so deliver others from it.",
      },
      {
        q: 15,
        question: "What kind of mediator and deliverer, then, must we seek?",
        answer:
          "One who is truly man and perfectly righteous, and yet more powerful than all creatures — that is, one who is at the same time true God.",
      },
    ],
  },
  {
    ld: 6,
    part: 2,
    theme: "Christ, the perfect Mediator",
    qas: [
      {
        q: 16,
        question: "Why must He be a true and righteous man?",
        answer:
          "Because the justice of God requires that the same human nature which has sinned should make satisfaction for sin, and one who is himself a sinner cannot satisfy for others.",
      },
      {
        q: 17,
        question: "Why must He at the same time be true God?",
        answer:
          "That, by the power of His Godhead, He might bear in His humanity the burden of God's wrath, and might obtain for us and restore to us righteousness and life.",
      },
      {
        q: 18,
        question: "Who, then, is that Mediator who is at the same time true God and a true, righteous man?",
        answer:
          "Our Lord Jesus Christ, who became unto us wisdom from God — righteousness, sanctification, and redemption.",
      },
      {
        q: 19,
        question: "From where do you know this?",
        answer:
          "From the holy Gospel, which God Himself first revealed in paradise, afterward proclaimed by the patriarchs and prophets, foreshadowed by the sacrifices and other ceremonies of the law, and finally fulfilled by His beloved Son.",
      },
    ],
  },
  {
    ld: 7,
    part: 2,
    theme: "True faith",
    qas: [
      {
        q: 20,
        question: "Are all men, then, saved by Christ as they have perished in Adam?",
        answer:
          "No; only those who, by true faith, are engrafted into Him and receive all His benefits.",
      },
      {
        q: 21,
        question: "What is true faith?",
        answer:
          "True faith is not only a certain knowledge whereby I hold for truth all that God has revealed to us in His Word, but also a firm confidence which the Holy Spirit works in my heart by the Gospel, that not only to others, but to me also, remission of sins, everlasting righteousness, and salvation are freely given by God, merely of grace, only for the sake of Christ's merits.",
      },
      {
        q: 22,
        question: "What, then, is necessary for a Christian to believe?",
        answer: "All that is promised us in the Gospel, which the articles of our catholic, undoubted Christian faith summarize for us.",
      },
      {
        q: 23,
        question: "What are these articles?",
        answer:
          "I believe in God the Father almighty, Maker of heaven and earth. And in Jesus Christ, His only-begotten Son, our Lord; who was conceived by the Holy Spirit, born of the virgin Mary; suffered under Pontius Pilate, was crucified, dead, and buried; He descended into hell; the third day He rose again from the dead; He ascended into heaven, and sits at the right hand of God the Father almighty; from there He shall come to judge the living and the dead. I believe in the Holy Spirit; the holy catholic (universal) Church, the communion of saints; the forgiveness of sins; the resurrection of the body; and the life everlasting. Amen.",
      },
    ],
  },
  {
    ld: 8,
    part: 2,
    theme: "The Holy Trinity",
    qas: [
      {
        q: 24,
        question: "How are these articles divided?",
        answer:
          "Into three parts: the first of God the Father and our creation; the second of God the Son and our redemption; the third of God the Holy Spirit and our sanctification.",
      },
      {
        q: 25,
        question: "Since there is but one Divine Being, why do you speak of three: the Father, the Son, and the Holy Spirit?",
        answer:
          "Because God has so revealed Himself in His Word, that these three distinct Persons are the one, true, eternal God.",
      },
    ],
  },
  {
    ld: 9,
    part: 2,
    theme: "God the Father — the Creator",
    qas: [
      {
        q: 26,
        question: "What do you believe when you say: I believe in God the Father almighty, Maker of heaven and earth?",
        answer:
          "That the eternal Father of our Lord Jesus Christ, who, of nothing, made heaven and earth, with all that is in them, and who likewise upholds and governs them by His eternal counsel and providence, is, for the sake of Christ His Son, my God and my Father; in whom I so trust as to have no doubt that He will provide me with all things necessary for body and soul, and will also turn to my good whatever adversity He sends me in this valley of tears, since He is able to do it, being almighty God, and willing also, being a faithful Father.",
      },
    ],
  },
  {
    ld: 10,
    part: 2,
    theme: "Providence",
    qas: [
      {
        q: 27,
        question: "What do you understand by the providence of God?",
        answer:
          "The almighty and ever-present power of God whereby He still upholds, as it were by His own hand, heaven and earth, with all creatures, and so governs them that herbs and grass, rain and drought, fruitful and barren years, food and drink, health and sickness, riches and poverty — indeed, all things — come not by chance, but by His fatherly hand.",
      },
      {
        q: 28,
        question: "What does it profit us to know that God has created and by His providence still upholds all things?",
        answer:
          "That we may be patient in adversity, thankful in prosperity, and for what is future may have good confidence in our faithful God and Father, that no creature shall separate us from His love, since all creatures are so in His hand that without His will they cannot so much as move.",
      },
    ],
  },
  {
    ld: 11,
    part: 2,
    theme: "The name Jesus",
    qas: [
      {
        q: 29,
        question: "Why is the Son of God called Jesus, that is, Savior?",
        answer:
          "Because He saves us from our sins, and because salvation is to be sought or found in no other.",
      },
      {
        q: 30,
        question: "Do those then believe in the only Savior Jesus who seek their salvation and welfare from saints, of themselves, or anywhere else?",
        answer:
          "No; though they boast of Him in words, yet in deeds they deny the only Savior Jesus. For either Jesus is not a complete Savior, or those who by true faith receive this Savior must find in Him all that is necessary for their salvation.",
      },
    ],
  },
  {
    ld: 12,
    part: 2,
    theme: "Christ — anointed Prophet, Priest, and King",
    qas: [
      {
        q: 31,
        question: "Why is He called Christ — that is, Anointed?",
        answer:
          "Because He is ordained of God the Father, and anointed with the Holy Spirit, to be our chief Prophet and Teacher, who has fully revealed to us the secret counsel and will of God concerning our redemption; and our only High Priest, who, by the one sacrifice of His body, has redeemed us, and ever lives to make intercession for us with the Father; and our eternal King, who governs us by His Word and Spirit, and defends and preserves us in the salvation purchased for us.",
      },
      {
        q: 32,
        question: "But why are you called a Christian?",
        answer:
          "Because by faith I am a member of Christ and so partaker of His anointing; that I may confess His name, present myself a living sacrifice of thankfulness to Him, and with a free and good conscience fight against sin and Satan in this life, and afterwards reign with Him eternally over all creatures.",
      },
    ],
  },
  {
    ld: 13,
    part: 2,
    theme: "Christ the only-begotten Son — and our Lord",
    qas: [
      {
        q: 33,
        question: "Why is Christ called the only-begotten Son of God, since we also are children of God?",
        answer:
          "Because Christ alone is the eternal, natural Son of God; but we are children of God by adoption, through grace, for His sake.",
      },
      {
        q: 34,
        question: "Why do you call Him our Lord?",
        answer:
          "Because not with silver or gold, but with His precious blood, He has redeemed and purchased us, body and soul, from sin and from all the power of the devil, to be His own.",
      },
    ],
  },
  {
    ld: 14,
    part: 2,
    theme: "Conceived by the Holy Spirit, born of the virgin Mary",
    qas: [
      {
        q: 35,
        question: "What is the meaning of: 'conceived by the Holy Spirit, born of the virgin Mary'?",
        answer:
          "That the eternal Son of God, who is and continues true and eternal God, took upon Him the very nature of man, of the flesh and blood of the virgin Mary, by the operation of the Holy Spirit; that He might also be the true seed of David, like His brethren in all things, sin excepted.",
      },
      {
        q: 36,
        question: "What benefit do you receive from the holy conception and birth of Christ?",
        answer:
          "That He is our Mediator; and with His innocence and perfect holiness covers, in the sight of God, my sin, in which I was conceived.",
      },
    ],
  },
  {
    ld: 15,
    part: 2,
    theme: "Suffered, crucified, dead, buried",
    qas: [
      {
        q: 37,
        question: "What do you understand by the word 'suffered'?",
        answer:
          "That He, all the time of His life on earth, but especially at the end of it, sustained, in body and soul, the wrath of God against the sin of the whole human race; that so by His suffering, as the only atoning sacrifice, He might redeem our body and soul from everlasting damnation, and obtain for us the grace of God, righteousness, and eternal life.",
      },
      {
        q: 38,
        question: "Why did He suffer under Pontius Pilate as judge?",
        answer:
          "That He, being innocent, might be condemned by an earthly judge, and thereby deliver us from the severe judgment of God to which we were exposed.",
      },
      {
        q: 39,
        question: "Is there anything more in His being crucified than if He had died some other death?",
        answer:
          "Yes; for thereby I am assured that He took upon Him the curse which lay upon me; for the death of the cross was accursed of God.",
      },
    ],
  },
  {
    ld: 16,
    part: 2,
    theme: "Why Christ had to die — and what His death gives us",
    qas: [
      {
        q: 40,
        question: "Why was it necessary for Christ to humble Himself even unto death?",
        answer:
          "Because, by the justice and truth of God, satisfaction for our sins could be made no other way than by the death of the Son of God.",
      },
      {
        q: 41,
        question: "Why was He buried?",
        answer: "To show thereby that He was really dead.",
      },
      {
        q: 42,
        question: "Since, then, Christ died for us, why must we also die?",
        answer:
          "Our death is not a satisfaction for our sin, but only a dying to sin and an entering into eternal life.",
      },
      {
        q: 43,
        question: "What further benefit do we receive from the sacrifice and death of Christ on the cross?",
        answer:
          "That by His power our old man is with Him crucified, slain, and buried, that so the evil lusts of the flesh may no more reign in us, but that we may offer ourselves a sacrifice of thanksgiving to Him.",
      },
      {
        q: 44,
        question: "Why is there added: 'He descended into hell'?",
        answer:
          "That in my greatest temptations I may be assured that Christ my Lord, by His inexpressible anguish, pains, and terrors which He suffered in His soul on the cross and before, has delivered me from the anguish and torment of hell.",
      },
    ],
  },
  {
    ld: 17,
    part: 2,
    theme: "Resurrection",
    qas: [
      {
        q: 45,
        question: "What benefit do we receive from the resurrection of Christ?",
        answer:
          "First, by His resurrection He has overcome death, that He might make us partakers of the righteousness which He had purchased for us by His death. Second, we also are now by His power raised up to a new life. Third, the resurrection of Christ is a sure pledge of our blessed resurrection.",
      },
    ],
  },
  {
    ld: 18,
    part: 2,
    theme: "Ascension",
    qas: [
      {
        q: 46,
        question: "How do you understand the words: 'He ascended into heaven'?",
        answer:
          "That Christ, in the sight of His disciples, was taken up from the earth into heaven, and continues there for our benefit until He comes again to judge the living and the dead.",
      },
      {
        q: 47,
        question: "Is not Christ, then, with us even to the end of the world, as He has promised?",
        answer:
          "Christ is true man and true God. According to His human nature He is no more on earth; but according to His Godhead, majesty, grace, and Spirit, He is at no time absent from us.",
      },
      {
        q: 48,
        question: "But are not the two natures in Christ separated from each other in this way, if the humanity is not wherever the Godhead is?",
        answer:
          "Not at all; for since the Godhead is incomprehensible and everywhere present, it must follow that it is indeed beyond the bounds of the human nature it has assumed, and yet is none the less in this human nature, and remains personally united with it.",
      },
      {
        q: 49,
        question: "What benefit do we receive from Christ's ascension into heaven?",
        answer:
          "First, that He is our Advocate in the presence of His Father in heaven. Second, that we have our flesh in heaven as a sure pledge that He, as the Head, will also take us up, His members, unto Himself. Third, that He sends us His Spirit as an earnest, by whose power we seek the things that are above, where Christ sits at the right hand of God, and not things on the earth.",
      },
    ],
  },
  {
    ld: 19,
    part: 2,
    theme: "Christ at the right hand — coming to judge",
    qas: [
      {
        q: 50,
        question: "Why is it added: 'And sits at the right hand of God'?",
        answer:
          "Because Christ ascended into heaven for this end: that He might appear as the Head of His Church, by whom the Father governs all things.",
      },
      {
        q: 51,
        question: "What does this glory of Christ our Head profit us?",
        answer:
          "First, that by His Holy Spirit He pours out heavenly gifts upon us, His members. Second, that by His power He defends and preserves us against all enemies.",
      },
      {
        q: 52,
        question: "What comfort is it to you that Christ shall come again to judge the living and the dead?",
        answer:
          "That in all my sorrows and persecutions I, with uplifted head, look for the very same who has before offered Himself for me to the judgment of God, and removed all curse from me, to come as Judge from heaven; who shall cast all His and my enemies into everlasting condemnation, but shall take me with all His chosen ones to Himself into heavenly joy and glory.",
      },
    ],
  },
  {
    ld: 20,
    part: 2,
    theme: "The Holy Spirit",
    qas: [
      {
        q: 53,
        question: "What do you believe concerning the Holy Spirit?",
        answer:
          "First, that He is co-eternal God with the Father and the Son. Second, that He is also given to me, to make me by true faith partaker of Christ and all His benefits, to comfort me, and to abide with me forever.",
      },
    ],
  },
  {
    ld: 21,
    part: 2,
    theme: "The Holy Catholic Church · forgiveness · resurrection · life everlasting",
    qas: [
      {
        q: 54,
        question: "What do you believe concerning the holy catholic (universal) Church?",
        answer:
          "That the Son of God, from the beginning to the end of the world, gathers, defends, and preserves to Himself, by His Spirit and Word, out of the whole human race, a Church chosen to everlasting life, agreeing in true faith; and that I am, and forever shall remain, a living member of it.",
      },
      {
        q: 55,
        question: "What do you understand by the communion of saints?",
        answer:
          "First, that all and every one who believes, being members of Christ, are in common partakers of Him and of all His riches and gifts. Second, that each one must know it to be his duty readily and cheerfully to use his gifts for the advantage and salvation of other members.",
      },
      {
        q: 56,
        question: "What do you believe concerning the forgiveness of sins?",
        answer:
          "That God, for the sake of Christ's satisfaction, will no more remember my sins, nor my sinful nature, against which I have to struggle all my life long; but graciously imputes to me the righteousness of Christ, that I may never be condemned before the judgment seat of God.",
      },
      {
        q: 57,
        question: "What comfort does the resurrection of the body afford you?",
        answer:
          "That not only my soul, after this life, shall immediately be taken up to Christ, its Head, but also that this my body, raised by the power of Christ, shall be reunited with my soul, and made like to the glorious body of Christ.",
      },
      {
        q: 58,
        question: "What comfort do you receive from the article of life everlasting?",
        answer:
          "That, since I now feel in my heart the beginning of eternal joy, I shall after this life possess complete blessedness, such as eye has not seen, nor ear heard, nor has it entered into the heart of man to conceive — therein to praise God forever.",
      },
    ],
  },
  {
    ld: 22,
    part: 2,
    theme: "Justification — the heart of the Gospel",
    qas: [
      {
        q: 59,
        question: "What does it now profit you that you believe all this?",
        answer:
          "That I am righteous in Christ before God, and an heir of eternal life.",
      },
      {
        q: 60,
        question: "How are you righteous before God?",
        answer:
          "Only by true faith in Jesus Christ; so that, though my conscience accuse me that I have grievously sinned against all the commandments of God, and have never kept any of them, and am still prone always to all evil, yet God, without any merit of mine, of mere grace, grants and imputes to me the perfect satisfaction, righteousness, and holiness of Christ, as if I had never committed nor had any sin, and had myself accomplished all the obedience which Christ has fulfilled for me; if only I accept such benefit with a believing heart.",
      },
      {
        q: 61,
        question: "Why do you say that you are righteous by faith only?",
        answer:
          "Not that I am acceptable to God on account of the worthiness of my faith, but because only the satisfaction, righteousness, and holiness of Christ is my righteousness before God; and I can receive the same and make it my own in no other way than by faith only.",
      },
    ],
  },
  {
    ld: 23,
    part: 2,
    theme: "Why not works",
    qas: [
      {
        q: 62,
        question: "Why cannot our good works be the whole or any part of our righteousness before God?",
        answer:
          "Because the righteousness which can stand before the judgment seat of God must be perfect throughout and wholly conformable to the divine law; whereas even our best works in this life are all imperfect and defiled with sin.",
      },
      {
        q: 63,
        question: "Do our good works merit nothing, even though it is God's will to reward them in this and in the future life?",
        answer:
          "The reward comes not of merit, but of grace.",
      },
      {
        q: 64,
        question: "But does not this doctrine make men careless and profane?",
        answer:
          "No; for it is impossible that those who are engrafted into Christ by true faith should not bring forth fruits of thankfulness.",
      },
    ],
  },
  {
    ld: 24,
    part: 2,
    theme: "Why faith — and not works — saves",
    qas: [
      {
        q: 65,
        question: "Since, then, we are made partakers of Christ and all His benefits by faith only, from where does this faith come?",
        answer:
          "From the Holy Spirit, who works it in our hearts by the preaching of the Gospel, and confirms it by the use of the holy Sacraments.",
      },
      {
        q: 66,
        question: "What are the Sacraments?",
        answer:
          "Visible, holy signs and seals, instituted of God to the end that by the use thereof He may the more fully declare and seal to us the promise of the Gospel — namely, that He grants us freely the remission of sin and life eternal for the sake of the one sacrifice of Christ accomplished on the cross.",
      },
      {
        q: 67,
        question: "Are both Word and Sacraments designed to direct our faith to the one sacrifice of Jesus Christ on the cross?",
        answer:
          "Yes, indeed; for the Holy Spirit teaches us in the Gospel, and assures us by the holy Sacraments, that our whole salvation stands in the one sacrifice of Christ made for us on the cross.",
      },
      {
        q: 68,
        question: "How many Sacraments has Christ instituted in the New Testament?",
        answer: "Two: holy Baptism and the holy Supper.",
      },
    ],
  },
  {
    ld: 25,
    part: 2,
    theme: "Holy Baptism",
    qas: [
      {
        q: 69,
        question: "How is it signified and sealed to you in holy Baptism that you have part in the one sacrifice of Christ on the cross?",
        answer:
          "Thus: that Christ has appointed this outward washing with water, and has joined therewith this promise: that I am washed with His blood and Spirit from the pollution of my soul — that is, from all my sins — as certainly as I am washed outwardly with water.",
      },
      {
        q: 70,
        question: "What is it to be washed with the blood and Spirit of Christ?",
        answer:
          "It is to have the forgiveness of sins from God, through grace, for the sake of Christ's blood; and also to be renewed by the Holy Spirit, and sanctified to be members of Christ, that so we may more and more die unto sin, and lead holy and blameless lives.",
      },
      {
        q: 71,
        question: "Where has Christ promised that we are as certainly washed with His blood and Spirit as with the water of Baptism?",
        answer:
          "In the institution of Baptism, which runs thus: 'Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.' And: 'Whoever believes and is baptized will be saved.'",
      },
    ],
  },
  {
    ld: 26,
    part: 2,
    theme: "What baptism is — and is not",
    qas: [
      {
        q: 72,
        question: "Is, then, the outward washing of water itself the washing away of sins?",
        answer:
          "No; for only the blood of Jesus Christ and the Holy Spirit cleanses us from all sin.",
      },
      {
        q: 73,
        question: "Why then does the Holy Spirit call Baptism the washing of regeneration and the washing away of sins?",
        answer:
          "God speaks thus not without great cause: to teach us that, as the filth of the body is taken away by water, so our sins are taken away by the blood and Spirit of Christ; and even more, that by this divine pledge and token He may assure us that we are as truly washed from our sins spiritually as our bodies are washed with water.",
      },
      {
        q: 74,
        question: "Are infants also to be baptized?",
        answer:
          "Yes; for since they, as well as adults, belong to the covenant and Church of God, and since redemption from sin by the blood of Christ, and the Holy Spirit who works faith, are promised to them no less than to adults, they must also by Baptism, as a sign of the covenant, be received into the Christian Church, and be distinguished from the children of unbelievers — as was done in the old covenant by circumcision, in place of which Baptism is instituted in the new.",
      },
    ],
  },
  {
    ld: 27,
    part: 2,
    theme: "The Lord's Supper",
    qas: [
      {
        q: 75,
        question: "How is it signified and sealed to you in the holy Supper that you partake of the one sacrifice of Christ?",
        answer:
          "Thus: that Christ has commanded me and all believers to eat of this broken bread and drink of this cup in remembrance of Him, adding these promises: first, that His body was as certainly offered and broken for me, and His blood shed for me, as I see with my eyes the bread of the Lord broken and the cup given to me. Second, that He Himself feeds and nourishes my soul to everlasting life with His crucified body and shed blood, as assuredly as I receive from the hand of the minister and taste with my mouth the bread and cup of the Lord, which are given me as certain tokens of the body and blood of Christ.",
      },
    ],
  },
  {
    ld: 28,
    part: 2,
    theme: "Communion with Christ in the Supper",
    qas: [
      {
        q: 76,
        question: "What is it to eat the crucified body and drink the shed blood of Christ?",
        answer:
          "It is not only to embrace with a believing heart all the sufferings and death of Christ, and thereby to obtain the pardon of sin and life eternal, but also, besides that, to become more and more united to His sacred body, by the Holy Spirit, who dwells both in Christ and in us; so that we, though Christ is in heaven and we are on earth, are nevertheless flesh of His flesh and bone of His bones, and live and are governed forever by one Spirit, as members of the same body are by one soul.",
      },
      {
        q: 77,
        question: "Where has Christ promised that He will as certainly feed and nourish believers with His body and blood, as they eat of this broken bread and drink of this cup?",
        answer:
          "In the institution of the Supper, which says: 'The Lord Jesus on the night when He was betrayed took bread…'",
      },
    ],
  },
  {
    ld: 29,
    part: 2,
    theme: "How Christ is present in the Supper",
    qas: [
      {
        q: 78,
        question: "Do, then, the bread and wine become the very body and blood of Christ?",
        answer:
          "No; but as the water in Baptism is not changed into the blood of Christ, nor becomes the washing away of sins itself, so also in the Lord's Supper the holy bread does not become the body of Christ itself, but is a sign and assurance of those things that are sealed to us by it.",
      },
      {
        q: 79,
        question: "Why then does Christ call the bread His body, and the cup His blood?",
        answer:
          "He does this not without great cause; namely, that He may teach us that, as bread and wine sustain this temporal life, so His crucified body and shed blood are the true food and drink of our souls to eternal life; and even more, that by these visible signs and pledges He may assure us that we are as really partakers of His true body and blood, by the operation of the Holy Spirit, as we receive these signs by the bodily mouth.",
      },
    ],
  },
  {
    ld: 30,
    part: 2,
    theme: "The Supper — for whom, against what",
    qas: [
      {
        q: 80,
        question: "What difference is there between the Lord's Supper and the Roman Mass?",
        answer:
          "The Lord's Supper testifies to us that we have full pardon of all our sins by the one sacrifice of Jesus Christ, which He Himself once accomplished on the cross; and that by the Holy Spirit we are engrafted into Christ, who, according to His human nature, is now not on earth, but in heaven, at the right hand of God His Father, and there will be worshiped by us.",
      },
      {
        q: 81,
        question: "For whom is the Lord's Supper instituted?",
        answer:
          "For those who are truly displeased with themselves for their sins, yet trust that these are forgiven them for the sake of Christ, and that their remaining infirmity is covered by His sufferings and death; and who also desire more and more to strengthen their faith and to amend their life.",
      },
      {
        q: 82,
        question: "Are they also to be admitted to this Supper who, by their confession and life, show themselves to be unbelieving and ungodly?",
        answer:
          "No; for thus the covenant of God is profaned, and His wrath kindled against the whole congregation. Therefore the Christian Church is in duty bound, according to the appointment of Christ and His apostles, to exclude such persons until they amend their lives.",
      },
    ],
  },
  {
    ld: 31,
    part: 2,
    theme: "The keys of the kingdom",
    qas: [
      {
        q: 83,
        question: "What is the office of the keys?",
        answer:
          "The preaching of the holy Gospel and Christian discipline; by these two the kingdom of heaven is opened to believers and shut against unbelievers.",
      },
      {
        q: 84,
        question: "How is the kingdom of heaven opened and shut by the preaching of the holy Gospel?",
        answer:
          "Thus: when, according to the command of Christ, it is proclaimed and openly testified to believers, every one of them, that as often as they accept the promise of the Gospel by a true faith, all their sins are really forgiven them of God for the sake of Christ's merits; and on the contrary, when it is proclaimed to all unbelievers that the wrath of God and eternal condemnation abide on them so long as they are not converted.",
      },
      {
        q: 85,
        question: "How is the kingdom of heaven shut and opened by Christian discipline?",
        answer:
          "Thus: that, according to the command of Christ, those who, under the name of Christian, hold unchristian doctrines or live unchristian lives, after repeated brotherly admonitions cannot turn from their errors or evil ways, are complained of to the Church, or to those appointed by the Church; and if they do not regard their admonitions, are by them forbidden the use of the Sacraments, and so excluded from the Christian congregation, and by God Himself from the kingdom of Christ; and are again received as members of Christ and His Church when they promise and show real amendment.",
      },
    ],
  },
  {
    ld: 32,
    part: 3,
    theme: "Of Gratitude — why we do good works",
    qas: [
      {
        q: 86,
        question: "Since, then, we are redeemed from our misery by grace through Christ, without any merit of ours, why should we do good works?",
        answer:
          "Because Christ, having redeemed us by His blood, also renews us by His Holy Spirit after His own image, that with our whole life we show ourselves thankful to God for His blessing, and that He may be glorified through us; then also that we ourselves may be assured of our faith by its fruits; and by our godly walk may win our neighbors also to Christ.",
      },
      {
        q: 87,
        question: "Can those, then, not be saved who, continuing in their wicked and ungrateful lives, are not converted to God?",
        answer:
          "By no means; for, as the Scripture says, no unchaste person, idolater, adulterer, thief, covetous person, drunkard, slanderer, or extortioner — nor any such like — shall inherit the kingdom of God.",
      },
    ],
  },
  {
    ld: 33,
    part: 3,
    theme: "True repentance",
    qas: [
      {
        q: 88,
        question: "Of how many parts does the true repentance or conversion of man consist?",
        answer:
          "Of two parts: the dying of the old man, and the making alive of the new.",
      },
      {
        q: 89,
        question: "What is the dying of the old man?",
        answer:
          "Heartfelt sorrow for sin, causing us to hate and turn from it always more and more.",
      },
      {
        q: 90,
        question: "What is the making alive of the new man?",
        answer:
          "Heartfelt joy in God through Christ, and a love and delight to live according to the will of God in all good works.",
      },
      {
        q: 91,
        question: "But what are good works?",
        answer:
          "Only those which proceed from a true faith, are done according to the law of God, and to His glory; and not such as rest on our own opinion or the commandments of men.",
      },
    ],
  },
  {
    ld: 34,
    part: 3,
    theme: "The Law — the first commandment",
    qas: [
      {
        q: 92,
        question: "What is the law of God?",
        answer:
          "God spoke all these words, saying: 'I am the LORD your God, who brought you out of the land of Egypt, out of the house of slavery. You shall have no other gods before Me…' (the Ten Commandments in full, Exodus 20:2-17).",
      },
      {
        q: 93,
        question: "How are these commandments divided?",
        answer:
          "Into two tables: the first of which teaches in four commandments what duties we owe to God; the second, in six, what duties we owe to our neighbor.",
      },
      {
        q: 94,
        question: "What does God require in the first commandment?",
        answer:
          "That, on peril of my soul's salvation, I avoid and flee all idolatry, sorcery, enchantments, invocation of saints or of other creatures; and that I rightly acknowledge the only true God, trust in Him alone, with all humility and patience expect all good from Him only, and love, fear, and honor Him with my whole heart.",
      },
      {
        q: 95,
        question: "What is idolatry?",
        answer:
          "It is, in place of, or alongside of, the one true God who has revealed Himself in His Word, to imagine or have anything else in which to put one's trust.",
      },
    ],
  },
  {
    ld: 35,
    part: 3,
    theme: "The second commandment — no images",
    qas: [
      {
        q: 96,
        question: "What does God require in the second commandment?",
        answer:
          "That we should not represent Him by any visible form, nor worship Him in any other way than He has commanded in His Word.",
      },
      {
        q: 97,
        question: "May we not, then, make any image at all?",
        answer:
          "God may not and cannot be imaged in any way; as for creatures, though they may indeed be imaged, yet God forbids the making or having of any image of them in order to worship them, or to serve God by them.",
      },
      {
        q: 98,
        question: "But may not pictures be tolerated in churches as books for the people?",
        answer:
          "No; for we should not be wiser than God, who will not have His people taught by dumb idols, but by the living preaching of His Word.",
      },
    ],
  },
  {
    ld: 36,
    part: 3,
    theme: "The third commandment — God's name",
    qas: [
      {
        q: 99,
        question: "What is required in the third commandment?",
        answer:
          "That we not only by cursing or by false swearing, but also by unnecessary oaths, must not profane or abuse the name of God, nor by silence or connivance be partakers of such horrible sins in others; and, in short, that we use the holy name of God in no other way than with fear and reverence, that He may be rightly confessed and called upon by us, and be glorified in all our words and works.",
      },
      {
        q: 100,
        question: "Is, then, the profaning of God's name by swearing and cursing so grievous a sin that His wrath is kindled against those who do not, as much as they are able, hinder and forbid the same?",
        answer:
          "Yes, truly; for no sin is greater or provokes God's wrath more than the profaning of His name.",
      },
    ],
  },
  {
    ld: 37,
    part: 3,
    theme: "Oaths",
    qas: [
      {
        q: 101,
        question: "May we then swear an oath by the name of God in a godly manner?",
        answer:
          "Yes, when the magistrate requires it of his subjects, or when necessity demands it, in order thereby to maintain and promote fidelity and truth, to the glory of God and the welfare of our neighbor; for such an oath is grounded in God's Word.",
      },
      {
        q: 102,
        question: "May we also swear by saints or other creatures?",
        answer:
          "No; for a lawful oath is an invocation of God as the only searcher of hearts. This honor is due to no creature.",
      },
    ],
  },
  {
    ld: 38,
    part: 3,
    theme: "The fourth commandment — Sabbath",
    qas: [
      {
        q: 103,
        question: "What does God require in the fourth commandment?",
        answer:
          "First, that the ministry of the Gospel and the schools be maintained; and that I, especially on the day of rest, diligently frequent the church of God, to hear God's Word, to use the Sacraments, to call publicly upon the Lord, and to give Christian alms. Second, that all the days of my life I rest from my evil works, let the Lord work in me by His Spirit, and thus begin in this life the eternal Sabbath.",
      },
    ],
  },
  {
    ld: 39,
    part: 3,
    theme: "The fifth commandment — honor authorities",
    qas: [
      {
        q: 104,
        question: "What does God require in the fifth commandment?",
        answer:
          "That I show all honor, love, and faithfulness to my father and mother, and to all in authority over me; submit myself with due obedience to their good instruction and correction; and also bear patiently with their weaknesses, since it pleases God to govern us by their hand.",
      },
    ],
  },
  {
    ld: 40,
    part: 3,
    theme: "The sixth commandment — do not murder",
    qas: [
      {
        q: 105,
        question: "What does God require in the sixth commandment?",
        answer:
          "That I do not revile, hate, insult, or kill my neighbor either in deed or in thought, word, or gesture, much less in deed, whether by myself or by another; but lay aside all desire of revenge; also, that I do not harm myself, nor willfully run into danger.",
      },
      {
        q: 106,
        question: "Does this commandment speak only of killing?",
        answer:
          "No; but in forbidding murder, God teaches us that He abhors the root of murder — namely, envy, hatred, anger, and the desire of revenge — and that He regards all these as murder.",
      },
      {
        q: 107,
        question: "But is it enough that we do not kill our neighbor in any such way?",
        answer:
          "No; for in condemning envy, hatred, and anger, God commands us to love our neighbor as ourselves, to show patience, peace, meekness, mercy, and kindness toward him, and to prevent his hurt as much as in us lies; even to do good to our enemies.",
      },
    ],
  },
  {
    ld: 41,
    part: 3,
    theme: "The seventh commandment — adultery",
    qas: [
      {
        q: 108,
        question: "What does the seventh commandment teach us?",
        answer:
          "That all unchastity is condemned by God, and that therefore we must abhor it with all our hearts, and live chastely and modestly, whether in holy wedlock or in single life.",
      },
      {
        q: 109,
        question: "Does God forbid in this commandment only such gross sins as adultery?",
        answer:
          "Since both our body and soul are temples of the Holy Spirit, it is His will that we should keep both pure and holy; therefore He forbids all unchaste actions, gestures, words, thoughts, desires, and whatever can entice men thereto.",
      },
    ],
  },
  {
    ld: 42,
    part: 3,
    theme: "The eighth commandment — do not steal",
    qas: [
      {
        q: 110,
        question: "What does God forbid in the eighth commandment?",
        answer:
          "God forbids not only such theft and robbery as are punished by the magistrate, but He comprehends under the name of theft all wicked tricks and devices, whereby we design to appropriate to ourselves the goods which belong to our neighbor; whether by force or under the appearance of right — as unjust weights, ells, measures, wares, coins, usury, or by any means forbidden of God; also all covetousness, and all useless waste of His gifts.",
      },
      {
        q: 111,
        question: "But what does God require of you in this commandment?",
        answer:
          "That I promote the advantage of my neighbor in every way I can, deal with him as I would have others deal with me, and labor faithfully, that I may be able to relieve the needy.",
      },
    ],
  },
  {
    ld: 43,
    part: 3,
    theme: "The ninth commandment — bear no false witness",
    qas: [
      {
        q: 112,
        question: "What is required in the ninth commandment?",
        answer:
          "That I bear false witness against no one, twist no one's words, be no backbiter or slanderer, condemn no one rashly or unheard; but that I avoid every kind of lying and deceit as the works of the devil, on pain of God's heavy wrath; and in matters of judgment and justice, love the truth, sincerely speak and confess it, and also vindicate and promote the honor and good name of my neighbor.",
      },
    ],
  },
  {
    ld: 44,
    part: 3,
    theme: "The tenth commandment — do not covet",
    qas: [
      {
        q: 113,
        question: "What is required in the tenth commandment?",
        answer:
          "That even the least inclination or thought contrary to any of God's commandments never rise in our heart; but that with our whole heart we always hate all sin, and take pleasure in all righteousness.",
      },
      {
        q: 114,
        question: "But can those who are converted to God keep these commandments perfectly?",
        answer:
          "No; but even the holiest men, while in this life, have only a small beginning of this obedience; yet so that, with earnest purpose, they begin to live not only according to some, but all the commandments of God.",
      },
      {
        q: 115,
        question: "Why then will God have the Ten Commandments so strictly preached, since in this life no one can keep them?",
        answer:
          "First, that all our life long we may learn more and more to know our sinful nature, and so the more earnestly seek forgiveness of sins and righteousness in Christ; second, that we may continually strive and pray to God for the grace of the Holy Spirit, that we may become more and more conformable to the image of God, until we attain to the perfection proposed unto us, in the life to come.",
      },
    ],
  },
  {
    ld: 45,
    part: 3,
    theme: "Why we pray",
    qas: [
      {
        q: 116,
        question: "Why is prayer necessary for Christians?",
        answer:
          "Because it is the chief part of thankfulness which God requires of us, and because God will give His grace and Holy Spirit only to those who, with hearty sighing, unceasingly beg them of Him, and thank Him for them.",
      },
      {
        q: 117,
        question: "What is contained in a prayer which pleases God and is heard by Him?",
        answer:
          "First, that we from the heart call upon the one true God only, who has revealed Himself to us in His Word, for all that He has commanded us to ask of Him; second, that we thoroughly know our need and misery, that so we may humble ourselves in the presence of His divine majesty; third, that we be firmly assured that He, notwithstanding our unworthiness, will, for the sake of Christ our Lord, certainly hear our prayer, as He has promised us in His Word.",
      },
      {
        q: 118,
        question: "What has God commanded us to ask of Him?",
        answer:
          "All things necessary for soul and body, which Christ our Lord has comprised in that prayer which He Himself taught us.",
      },
      {
        q: 119,
        question: "What is that prayer?",
        answer:
          "Our Father in heaven, hallowed be Your name. Your kingdom come. Your will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from the evil one. For Yours is the kingdom and the power and the glory, forever. Amen.",
      },
    ],
  },
  {
    ld: 46,
    part: 3,
    theme: "'Our Father in heaven'",
    qas: [
      {
        q: 120,
        question: "Why has Christ commanded us to address God thus: 'Our Father'?",
        answer:
          "To awaken in us, at the very beginning of our prayer, that childlike reverence and trust toward God which should be the ground of our prayer — namely, that God has become our Father through Christ, and will much less deny us what we ask of Him in true faith, than our earthly parents will refuse us earthly things.",
      },
      {
        q: 121,
        question: "Why is it added: 'in heaven'?",
        answer:
          "That we may have no earthly thought of the heavenly majesty of God, and may expect from His almighty power all things necessary for body and soul.",
      },
    ],
  },
  {
    ld: 47,
    part: 3,
    theme: "First petition — 'Hallowed be Your name'",
    qas: [
      {
        q: 122,
        question: "What is the first petition?",
        answer:
          "'Hallowed be Your name.' That is: grant us first rightly to know You, and to hallow, magnify, and praise You in all Your works, in which Your power, wisdom, goodness, justice, mercy, and truth shine forth; and so to order our whole life, our thoughts, words, and works, that Your name may never be blasphemed, but rather honored and praised on our account.",
      },
    ],
  },
  {
    ld: 48,
    part: 3,
    theme: "Second petition — 'Your kingdom come'",
    qas: [
      {
        q: 123,
        question: "What is the second petition?",
        answer:
          "'Your kingdom come.' That is: so rule us by Your Word and Spirit that more and more we submit ourselves unto You; preserve and increase Your Church; destroy the works of the devil, every power that exalts itself against You, and every conspiracy against Your holy Word; until the perfection of Your kingdom comes, when You shall be all in all.",
      },
    ],
  },
  {
    ld: 49,
    part: 3,
    theme: "Third petition — 'Your will be done'",
    qas: [
      {
        q: 124,
        question: "What is the third petition?",
        answer:
          "'Your will be done, on earth as it is in heaven.' That is: grant that we and all men may renounce our own will and, without grumbling, obey Your will, which alone is good; and that everyone may attend to and discharge the duties of his vocation as willingly and faithfully as the angels do in heaven.",
      },
    ],
  },
  {
    ld: 50,
    part: 3,
    theme: "Fourth petition — 'Give us this day our daily bread'",
    qas: [
      {
        q: 125,
        question: "What is the fourth petition?",
        answer:
          "'Give us this day our daily bread.' That is: be pleased to provide us with all things necessary for the body, that we may thereby acknowledge You to be the only fountain of all good, and that without Your blessing neither our care and labor, nor Your gifts, can profit us; and that we may therefore withdraw our trust from all creatures and place it on You alone.",
      },
    ],
  },
  {
    ld: 51,
    part: 3,
    theme: "Fifth petition — 'Forgive us our debts'",
    qas: [
      {
        q: 126,
        question: "What is the fifth petition?",
        answer:
          "'And forgive us our debts, as we also have forgiven our debtors.' That is: be pleased, for the sake of Christ's blood, not to impute to us, miserable sinners, our transgressions, nor the evil which still always cleaves to us; as we also find this witness of Your grace in us, that it is our full purpose heartily to forgive our neighbor.",
      },
    ],
  },
  {
    ld: 52,
    part: 3,
    theme: "Sixth petition · doxology · Amen",
    qas: [
      {
        q: 127,
        question: "What is the sixth petition?",
        answer:
          "'And lead us not into temptation, but deliver us from the evil one.' That is: since we are so weak in ourselves that we cannot stand a moment, and besides this, our deadly enemies — the devil, the world, and our own flesh — do not cease to assault us, be pleased to preserve and strengthen us by the power of Your Holy Spirit, that we may make firm stand against them and not be overcome in this spiritual warfare, until at last we obtain a complete victory.",
      },
      {
        q: 128,
        question: "How do you conclude this prayer?",
        answer:
          "'For Yours is the kingdom and the power and the glory, forever.' That is: all this we ask of You, because, as our King, having power over all things, You are both willing and able to give us all good; and that thereby not we, but Your holy name, may be glorified forever.",
      },
      {
        q: 129,
        question: "What does the word 'Amen' mean?",
        answer:
          "It means, So shall it truly and surely be. For my prayer is much more certainly heard by God than I feel in my heart that I desire these things of Him.",
      },
    ],
  },
];

export const catechismIntro = {
  title: "One question for every week of the year.",
  body: [
    "The Heidelberg Catechism (1563) is the warmest and most pastoral of the great Reformation catechisms. It walks through 129 questions over 52 weekly 'Lord's Days' in three movements: our misery without Christ, our deliverance through Christ, and our gratitude because of Christ.",
    "It begins with one of the most loved questions in all of Christianity: 'What is your only comfort in life and in death?' It ends with the meaning of 'Amen.' Between, it teaches the heart of the faith.",
    "Pick one Lord's Day each week. Read it slowly. Read it aloud. Let it pray you.",
  ],
};
