#!/usr/bin/env node
// Ingest the World English Bible (WEB) — public domain — from bible-api.com.
// Writes data/bible/text.ts as a single typed module the app imports at build time.
//
// Run:  npm run ingest-bible
// Optional:  npm run ingest-bible -- --books=john,romans,psalms
//
// WEB credit:  Michael Paul Johnson · eBible.org · Public domain
// bible-api.com:  https://bible-api.com/ (free, no key)

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT_PATH = resolve(REPO_ROOT, "data/bible/text.ts");

const CANON = [
  ["genesis", 50], ["exodus", 40], ["leviticus", 27], ["numbers", 36], ["deuteronomy", 34],
  ["joshua", 24], ["judges", 21], ["ruth", 4], ["1samuel", 31], ["2samuel", 24],
  ["1kings", 22], ["2kings", 25], ["1chronicles", 29], ["2chronicles", 36],
  ["ezra", 10], ["nehemiah", 13], ["esther", 10], ["job", 42], ["psalms", 150],
  ["proverbs", 31], ["ecclesiastes", 12], ["songofsongs", 8], ["isaiah", 66],
  ["jeremiah", 52], ["lamentations", 5], ["ezekiel", 48], ["daniel", 12],
  ["hosea", 14], ["joel", 3], ["amos", 9], ["obadiah", 1], ["jonah", 4],
  ["micah", 7], ["nahum", 3], ["habakkuk", 3], ["zephaniah", 3], ["haggai", 2],
  ["zechariah", 14], ["malachi", 4],
  ["matthew", 28], ["mark", 16], ["luke", 24], ["john", 21], ["acts", 28],
  ["romans", 16], ["1corinthians", 16], ["2corinthians", 13], ["galatians", 6],
  ["ephesians", 6], ["philippians", 4], ["colossians", 4],
  ["1thessalonians", 5], ["2thessalonians", 3], ["1timothy", 6], ["2timothy", 4],
  ["titus", 3], ["philemon", 1], ["hebrews", 13], ["james", 5],
  ["1peter", 5], ["2peter", 3], ["1john", 5], ["2john", 1], ["3john", 1],
  ["jude", 1], ["revelation", 22],
];

// Map our slug to the URL-friendly book name bible-api.com accepts.
const URL_NAME = {
  songofsongs: "song of solomon",
  "1samuel": "1 samuel",
  "2samuel": "2 samuel",
  "1kings": "1 kings",
  "2kings": "2 kings",
  "1chronicles": "1 chronicles",
  "2chronicles": "2 chronicles",
  "1corinthians": "1 corinthians",
  "2corinthians": "2 corinthians",
  "1thessalonians": "1 thessalonians",
  "2thessalonians": "2 thessalonians",
  "1timothy": "1 timothy",
  "2timothy": "2 timothy",
  "1peter": "1 peter",
  "2peter": "2 peter",
  "1john": "1 john",
  "2john": "2 john",
  "3john": "3 john",
};

const args = process.argv.slice(2);
const booksArg = args.find((a) => a.startsWith("--books="));
const onlyBooks = booksArg
  ? new Set(booksArg.replace("--books=", "").split(",").map((s) => s.trim()))
  : null;

async function fetchChapter(bookSlug, chapter) {
  const bookForUrl = URL_NAME[bookSlug] ?? bookSlug;
  const url = `https://bible-api.com/${encodeURIComponent(bookForUrl + " " + chapter)}?translation=web`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`bible-api.com ${res.status} for ${bookSlug} ${chapter}`);
  const data = await res.json();
  if (!data.verses || data.verses.length === 0) throw new Error(`no verses for ${bookSlug} ${chapter}`);
  return data.verses.map((v) => ({ v: v.verse, t: v.text.trim() }));
}

async function main() {
  const catalog = {};
  let totalChapters = 0;
  let failed = 0;

  for (const [slug, chapters] of CANON) {
    if (onlyBooks && !onlyBooks.has(slug)) continue;
    catalog[slug] = {};
    for (let c = 1; c <= chapters; c++) {
      try {
        const verses = await fetchChapter(slug, c);
        catalog[slug][c] = { book: slug, chapter: c, translation: "WEB", verses };
        totalChapters++;
        process.stdout.write(`\r  ${slug} ${c}/${chapters}      `);
        // Be gentle to the public API.
        await new Promise((r) => setTimeout(r, 80));
      } catch (err) {
        failed++;
        console.error(`\n  ! ${slug} ${c}: ${err.message}`);
      }
    }
    process.stdout.write("\n");
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  const header = `// Auto-generated by scripts/ingest-bible.mjs — do not edit by hand.
// Source: bible-api.com · World English Bible (WEB) · Public domain
// Generated at: ${new Date().toISOString()}
import type { ChapterText } from "./seed";

export const ingested: Record<string, Record<number, ChapterText>> = `;
  const body = JSON.stringify(catalog, null, 0);
  writeFileSync(OUT_PATH, header + body + ";\n", "utf8");

  console.log(
    `\nIngested ${totalChapters} chapters across ${Object.keys(catalog).length} books — ${failed} failure(s).`
  );
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
